[package]
name = "zup-rtfm"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"

[lib]
name = "rtfm"

[dependencies]
cortex-r = { path = "../cortex-r" }
microamp = { path = "../microamp" }
zup-rt = { path = "../zup-rt" }
zup-rtfm-macros = { path = "macros" }

[dependencies.heapless]
features = ["const-fn"]
version = "0.4.1"
