[package]
name = "cargo-amp"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
xmas-elf = "0.6.2"
exitfailure = "0.5.1"
clap = "2.32.0"
rustc_version = "0.2.3"
cargo-project = "0.2.1"
